name: Test Hardware Interface

on:
  push:
    branches: [main]

jobs:
  test-hardware-interface:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v7.0.0
      with:
        fetch-depth: 0
    - name: Assert and release reset
      run: |
        mkdir bin
        romulan src/rom.s --build --verbose -o bin/rom.bin
        romulan hardware upload bin/rom.bin --verbose
        romulan hardware capture --max-cycles 500
