name: Test Hardware Interface

on:
  push:
    branches: [main]

jobs:
  test-hardware-interface:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v7.0.0
      with:
        fetch-depth: 0
    - name: Build ROM
      run: |
        mkdir bin
        romulan src/rom.s --build -o bin/rom.bin
    - name: Upload ROM
      run: |
        romulan hardware upload bin/rom.bin --verbose
    - name: Execute program
      run: |
        romulan hardware capture --max-cycles 500 --timeout 45
